### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ronaldlangeveld** [fiixlabs/fiix-cmms-client-js#2]
I installed the client via NPM and importing it as follows in my NodeJS app, 

`const FiixCmmsClient = require('fiix-cmms-client');`

then I run the app to test as follows, with examples from the official documentation - https://fiixlabs.github.io/api-documentation/guide.html

```
const express = require('express')
const app = express()
const port = 3000
const FiixCmmsClient = require('fiix-cmms-client');

var fiixCmmsClient = new FiixCmmsClient();
fiixCmmsClient.setBaseUri('https://*****.macmms.com/api/');
fiixCmmsClient.setAppKey('****');
fiixCmmsClient.setAuthToken('*****');
fiixCmmsClient.setPKey('****');


app.get('/', (req, res) => {
    const xyz = function(ret) {
        if (!ret.error) {
          output(ret.objects);
        } else output(ret.error);
      };
    fiixCmmsClient.find({
        "className": "Asset",
        "fields": "id, strName, strDescription",
        "filters": [{"ql": "intAssetLocationID = ?", "parameters": [408608]}],
        "callback": xyz
      });
})

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})

```

I then run into the following error , most certainly coming from the `callback`.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseMaConnectJsonResponse (/Users/ronaldlangeveld/Dev/test/fiix/node_modules/fiix-cmms-client/index.js:437:21)
    at IncomingMessage.<anonymous> (/Users/ronaldlangeveld/Dev/test/fiix/node_modules/fiix-cmms-client/index.js:794:32)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[nodemon] app crashed - waiting for file changes before starting...
```

MacOS, latest NodeJS / Express.

**Comment by adeniyiodunlami** [comment]
Hi Ronald, 

Thank you for letting us know about this. However, I have tried using the client and I have not encountered this error. Can you try again with the latest version of the client? And possibly let us know the exact versions of Node and Express that you are using.

Regards,
Adebowale

**Comment by ronaldlangeveld** [comment]
Resolved. :)
